# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxMhimhOVxs1p1yCocPg7fbb0E-LIPGA

Name: Shruti Biradar

PRN : 202402040027


Group Members:   
Saishwari korade : 202402040028

Github Link : https://github.com/Shruti-2509/Assignment_5_LSTM

# LSTM Assignment

Dataset Loading
"""

import requests

url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"

text = requests.get(url).text

print("Dataset length:", len(text))

print(text[:500])

"""Convert to Sentences"""

sentences = text.split("\n")

sentences = [s.lower() for s in sentences if len(s) > 10]

print("Total sentences:", len(sentences))

"""Tokenization"""

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")

tokenizer.fit_on_texts(sentences)

total_words = 5000

print("Vocabulary size:", total_words)

"""Generate Sequences"""

input_sequences = []

for line in sentences:

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):

        n_gram = token_list[:i+1]

        input_sequences.append(n_gram)

print("Total sequences:", len(input_sequences))

"""Padding"""

from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

max_len = max(len(x) for x in input_sequences)

input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

X = input_sequences[:, :-1]

y = input_sequences[:, -1]

print(X.shape, y.shape)

"""LSTM Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

model = Sequential()

model.add(Embedding(5000, 128, input_shape=(max_len-1,)))

model.add(LSTM(128, return_sequences=True))

model.add(Dropout(0.2))

model.add(LSTM(64))

model.add(Dense(5000, activation='softmax'))

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

"""Train Model"""

history = model.fit(
    X,
    y,
    epochs=40,
    batch_size=64
)

"""Accuracy vs Loss"""

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'])
plt.title("Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.subplot(1,2,2)
plt.plot(history.history['loss'])
plt.title("Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.show()

"""Prediction Function"""

def predict_next_word(seed_text):

    token_list = tokenizer.texts_to_sequences([seed_text])[0]

    token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

    preds = model.predict(token_list)[0]

    top_k = preds.argsort()[-5:]

    predicted = np.random.choice(top_k)

    for word, index in tokenizer.word_index.items():

        if index == predicted:

            return word

"""Generate Text"""

def generate_text(seed_text, next_words):

    for _ in range(next_words):

        next_word = predict_next_word(seed_text)

        seed_text = seed_text + " " + next_word

    return seed_text

print(generate_text("my lord",5))
print(generate_text("i will",5))
print(generate_text("the king",5))

"""Save Model for FastAPI"""

model.save("lstm_model.h5")

import pickle

pickle.dump(tokenizer, open("tokenizer.pkl", "wb"))

"""Download"""

from google.colab import files

files.download("lstm_model.h5")
files.download("tokenizer.pkl")